// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: message.sql

package db

import (
	"context"
)

const createMessage = `-- name: CreateMessage :one
INSERT INTO messages (name, email, content)
VALUES ($1, $2, $3) RETURNING id, name, email, content, is_read, created_at, updated_at
`

type CreateMessageParams struct {
	Name    string `json:"name"`
	Email   string `json:"email"`
	Content string `json:"content"`
}

func (q *Queries) CreateMessage(ctx context.Context, arg CreateMessageParams) (Message, error) {
	row := q.db.QueryRow(ctx, createMessage, arg.Name, arg.Email, arg.Content)
	var i Message
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Email,
		&i.Content,
		&i.IsRead,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
