// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"database/sql"
	"time"

	"github.com/sqlc-dev/pqtype"
)

type Category struct {
	ID        int64          `json:"id"`
	Name      string         `json:"name"`
	Slug      string         `json:"slug"`
	Color     sql.NullString `json:"color"`
	CreatedAt time.Time      `json:"created_at"`
	UpdatedAt time.Time      `json:"updated_at"`
}

type Message struct {
	ID        int64        `json:"id"`
	Name      string       `json:"name"`
	Email     string       `json:"email"`
	Content   string       `json:"content"`
	IsRead    sql.NullBool `json:"is_read"`
	CreatedAt time.Time    `json:"created_at"`
	UpdatedAt time.Time    `json:"updated_at"`
}

type Profile struct {
	ID             int64                 `json:"id"`
	UserID         int64                 `json:"user_id"`
	Name           string                `json:"name"`
	Headline       sql.NullString        `json:"headline"`
	Role           sql.NullString        `json:"role"`
	BioShort       sql.NullString        `json:"bio_short"`
	BioLong        sql.NullString        `json:"bio_long"`
	Location       sql.NullString        `json:"location"`
	IsHireable     sql.NullBool          `json:"is_hireable"`
	Avatar         sql.NullString        `json:"avatar"`
	CvFiles        sql.NullString        `json:"cv_files"`
	HeroImageCodes sql.NullString        `json:"hero_image_codes"`
	Socials        pqtype.NullRawMessage `json:"socials"`
	CreatedAt      time.Time             `json:"created_at"`
	UpdatedAt      time.Time             `json:"updated_at"`
}

type Project struct {
	ID          int64          `json:"id"`
	Title       string         `json:"title"`
	Slug        string         `json:"slug"`
	Thumbnail   sql.NullString `json:"thumbnail"`
	Content     sql.NullString `json:"content"`
	DemoUrl     sql.NullString `json:"demo_url"`
	RepoUrl     sql.NullString `json:"repo_url"`
	IsFeatured  sql.NullBool   `json:"is_featured"`
	PublishedAt sql.NullTime   `json:"published_at"`
	ColumnOrder int32          `json:"column_order"`
	CategoryID  sql.NullInt64  `json:"category_id"`
	CreatedAt   time.Time      `json:"created_at"`
	UpdatedAt   time.Time      `json:"updated_at"`
}

type ProjectTag struct {
	ProjectID int64 `json:"project_id"`
	TagID     int64 `json:"tag_id"`
}

type ProjectTechStack struct {
	ProjectID   int64 `json:"project_id"`
	TechStackID int64 `json:"tech_stack_id"`
}

type Tag struct {
	ID         int64          `json:"id"`
	Name       string         `json:"name"`
	Slug       string         `json:"slug"`
	Color      sql.NullString `json:"color"`
	CategoryID sql.NullInt64  `json:"category_id"`
	CreatedAt  time.Time      `json:"created_at"`
	UpdatedAt  time.Time      `json:"updated_at"`
}

type TechStack struct {
	ID          int64          `json:"id"`
	Name        string         `json:"name"`
	Slug        string         `json:"slug"`
	Icon        sql.NullString `json:"icon"`
	ColumnOrder int32          `json:"column_order"`
	CreatedAt   time.Time      `json:"created_at"`
	UpdatedAt   time.Time      `json:"updated_at"`
}

type User struct {
	ID        int64     `json:"id"`
	Email     string    `json:"email"`
	Password  string    `json:"password"`
	CreatedAt time.Time `json:"created_at"`
	UpdatedAt time.Time `json:"updated_at"`
}

type WorkExperience struct {
	ID          int64          `json:"id"`
	Company     string         `json:"company"`
	Position    string         `json:"position"`
	Location    sql.NullString `json:"location"`
	StartDate   sql.NullString `json:"start_date"`
	EndDate     sql.NullString `json:"end_date"`
	IsCurrent   sql.NullBool   `json:"is_current"`
	Description sql.NullString `json:"description"`
	CreatedAt   time.Time      `json:"created_at"`
	UpdatedAt   time.Time      `json:"updated_at"`
	ColumnOrder int32          `json:"column_order"`
}

type WorkExperienceTag struct {
	WorkExperienceID int64 `json:"work_experience_id"`
	TagID            int64 `json:"tag_id"`
}

type WorkExperienceTechStack struct {
	WorkExperienceID int64 `json:"work_experience_id"`
	TechStackID      int64 `json:"tech_stack_id"`
}
