// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"database/sql"
	"time"
)

type Project struct {
	ID        int64          `json:"id"`
	Title     string         `json:"title"`
	Content   sql.NullString `json:"content"`
	CreatedAt time.Time      `json:"created_at"`
}

type User struct {
	ID        int64     `json:"id"`
	Email     string    `json:"email"`
	Password  string    `json:"password"`
	CreatedAt time.Time `json:"created_at"`
}
