// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: profile.sql

package db

import (
	"context"
	"database/sql"

	"github.com/sqlc-dev/pqtype"
)

const createProfile = `-- name: CreateProfile :one
INSERT INTO profiles (user_id, name, headline, role, bio_short, bio_long, location,
                      is_hireable, avatar, cv_files, hero_image_codes, socials)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12) RETURNING id, user_id, name, headline, role, bio_short, bio_long, location, is_hireable, avatar, cv_files, hero_image_codes, socials, created_at, updated_at
`

type CreateProfileParams struct {
	UserID         int64                 `json:"user_id"`
	Name           string                `json:"name"`
	Headline       sql.NullString        `json:"headline"`
	Role           sql.NullString        `json:"role"`
	BioShort       sql.NullString        `json:"bio_short"`
	BioLong        sql.NullString        `json:"bio_long"`
	Location       sql.NullString        `json:"location"`
	IsHireable     sql.NullBool          `json:"is_hireable"`
	Avatar         sql.NullString        `json:"avatar"`
	CvFiles        sql.NullString        `json:"cv_files"`
	HeroImageCodes sql.NullString        `json:"hero_image_codes"`
	Socials        pqtype.NullRawMessage `json:"socials"`
}

func (q *Queries) CreateProfile(ctx context.Context, arg CreateProfileParams) (Profile, error) {
	row := q.db.QueryRowContext(ctx, createProfile,
		arg.UserID,
		arg.Name,
		arg.Headline,
		arg.Role,
		arg.BioShort,
		arg.BioLong,
		arg.Location,
		arg.IsHireable,
		arg.Avatar,
		arg.CvFiles,
		arg.HeroImageCodes,
		arg.Socials,
	)
	var i Profile
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.Headline,
		&i.Role,
		&i.BioShort,
		&i.BioLong,
		&i.Location,
		&i.IsHireable,
		&i.Avatar,
		&i.CvFiles,
		&i.HeroImageCodes,
		&i.Socials,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getProfileByUserId = `-- name: GetProfileByUserId :one
SELECT id, user_id, name, headline, role, bio_short, bio_long, location, is_hireable, avatar, cv_files, hero_image_codes, socials, created_at, updated_at
FROM profiles
WHERE user_id = $1 LIMIT 1
`

func (q *Queries) GetProfileByUserId(ctx context.Context, userID int64) (Profile, error) {
	row := q.db.QueryRowContext(ctx, getProfileByUserId, userID)
	var i Profile
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.Headline,
		&i.Role,
		&i.BioShort,
		&i.BioLong,
		&i.Location,
		&i.IsHireable,
		&i.Avatar,
		&i.CvFiles,
		&i.HeroImageCodes,
		&i.Socials,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateProfile = `-- name: UpdateProfile :one
UPDATE profiles
SET name      = $2,
    headline  = $3,
    bio_short = $4
WHERE user_id = $1 RETURNING id, user_id, name, headline, role, bio_short, bio_long, location, is_hireable, avatar, cv_files, hero_image_codes, socials, created_at, updated_at
`

type UpdateProfileParams struct {
	UserID   int64          `json:"user_id"`
	Name     string         `json:"name"`
	Headline sql.NullString `json:"headline"`
	BioShort sql.NullString `json:"bio_short"`
}

func (q *Queries) UpdateProfile(ctx context.Context, arg UpdateProfileParams) (Profile, error) {
	row := q.db.QueryRowContext(ctx, updateProfile,
		arg.UserID,
		arg.Name,
		arg.Headline,
		arg.BioShort,
	)
	var i Profile
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.Headline,
		&i.Role,
		&i.BioShort,
		&i.BioLong,
		&i.Location,
		&i.IsHireable,
		&i.Avatar,
		&i.CvFiles,
		&i.HeroImageCodes,
		&i.Socials,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
