// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: project.sql

package db

import (
	"context"
	"database/sql"
)

const attachTagToProject = `-- name: AttachTagToProject :exec
INSERT INTO project_tags (project_id, tag_id)
VALUES ($1, $2)
`

type AttachTagToProjectParams struct {
	ProjectID int64 `json:"project_id"`
	TagID     int64 `json:"tag_id"`
}

func (q *Queries) AttachTagToProject(ctx context.Context, arg AttachTagToProjectParams) error {
	_, err := q.db.ExecContext(ctx, attachTagToProject, arg.ProjectID, arg.TagID)
	return err
}

const attachTechStackToProject = `-- name: AttachTechStackToProject :exec
INSERT INTO project_tech_stacks (project_id, tech_stack_id)
VALUES ($1, $2)
`

type AttachTechStackToProjectParams struct {
	ProjectID   int64 `json:"project_id"`
	TechStackID int64 `json:"tech_stack_id"`
}

func (q *Queries) AttachTechStackToProject(ctx context.Context, arg AttachTechStackToProjectParams) error {
	_, err := q.db.ExecContext(ctx, attachTechStackToProject, arg.ProjectID, arg.TechStackID)
	return err
}

const createProject = `-- name: CreateProject :one
INSERT INTO projects (title, slug, thumbnail, content, category_id, is_featured)
VALUES ($1, $2, $3, $4, $5, $6) RETURNING id, title, slug, thumbnail, content, demo_url, repo_url, is_featured, published_at, category_id, created_at, updated_at
`

type CreateProjectParams struct {
	Title      string         `json:"title"`
	Slug       string         `json:"slug"`
	Thumbnail  sql.NullString `json:"thumbnail"`
	Content    sql.NullString `json:"content"`
	CategoryID sql.NullInt64  `json:"category_id"`
	IsFeatured sql.NullBool   `json:"is_featured"`
}

func (q *Queries) CreateProject(ctx context.Context, arg CreateProjectParams) (Project, error) {
	row := q.db.QueryRowContext(ctx, createProject,
		arg.Title,
		arg.Slug,
		arg.Thumbnail,
		arg.Content,
		arg.CategoryID,
		arg.IsFeatured,
	)
	var i Project
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Slug,
		&i.Thumbnail,
		&i.Content,
		&i.DemoUrl,
		&i.RepoUrl,
		&i.IsFeatured,
		&i.PublishedAt,
		&i.CategoryID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getProject = `-- name: GetProject :one
SELECT id, title, slug, thumbnail, content, demo_url, repo_url, is_featured, published_at, category_id, created_at, updated_at
FROM projects
WHERE id = $1 LIMIT 1
`

func (q *Queries) GetProject(ctx context.Context, id int64) (Project, error) {
	row := q.db.QueryRowContext(ctx, getProject, id)
	var i Project
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Slug,
		&i.Thumbnail,
		&i.Content,
		&i.DemoUrl,
		&i.RepoUrl,
		&i.IsFeatured,
		&i.PublishedAt,
		&i.CategoryID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listProjects = `-- name: ListProjects :many
SELECT id, title, slug, thumbnail, content, demo_url, repo_url, is_featured, published_at, category_id, created_at, updated_at
FROM projects
ORDER BY created_at DESC
`

func (q *Queries) ListProjects(ctx context.Context) ([]Project, error) {
	rows, err := q.db.QueryContext(ctx, listProjects)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Project
	for rows.Next() {
		var i Project
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Slug,
			&i.Thumbnail,
			&i.Content,
			&i.DemoUrl,
			&i.RepoUrl,
			&i.IsFeatured,
			&i.PublishedAt,
			&i.CategoryID,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
