// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: project.sql

package db

import (
	"context"
	"database/sql"
)

const addTagToProject = `-- name: AddTagToProject :exec
INSERT INTO project_tags (project_id, tag_id)
VALUES ($1, $2)
`

type AddTagToProjectParams struct {
	ProjectID int64 `json:"project_id"`
	TagID     int64 `json:"tag_id"`
}

func (q *Queries) AddTagToProject(ctx context.Context, arg AddTagToProjectParams) error {
	_, err := q.db.ExecContext(ctx, addTagToProject, arg.ProjectID, arg.TagID)
	return err
}

const addTechStackToProject = `-- name: AddTechStackToProject :exec
INSERT INTO project_tech_stacks (project_id, tech_stack_id)
VALUES ($1, $2)
`

type AddTechStackToProjectParams struct {
	ProjectID   int64 `json:"project_id"`
	TechStackID int64 `json:"tech_stack_id"`
}

func (q *Queries) AddTechStackToProject(ctx context.Context, arg AddTechStackToProjectParams) error {
	_, err := q.db.ExecContext(ctx, addTechStackToProject, arg.ProjectID, arg.TechStackID)
	return err
}

const attachTagToProject = `-- name: AttachTagToProject :exec
INSERT INTO project_tags (project_id, tag_id)
VALUES ($1, $2)
`

type AttachTagToProjectParams struct {
	ProjectID int64 `json:"project_id"`
	TagID     int64 `json:"tag_id"`
}

func (q *Queries) AttachTagToProject(ctx context.Context, arg AttachTagToProjectParams) error {
	_, err := q.db.ExecContext(ctx, attachTagToProject, arg.ProjectID, arg.TagID)
	return err
}

const attachTechStackToProject = `-- name: AttachTechStackToProject :exec

INSERT INTO project_tech_stacks (project_id, tech_stack_id)
VALUES ($1, $2)
`

type AttachTechStackToProjectParams struct {
	ProjectID   int64 `json:"project_id"`
	TechStackID int64 `json:"tech_stack_id"`
}

// =============================================
// PIVOT TABLE QUERIES
// =============================================
func (q *Queries) AttachTechStackToProject(ctx context.Context, arg AttachTechStackToProjectParams) error {
	_, err := q.db.ExecContext(ctx, attachTechStackToProject, arg.ProjectID, arg.TechStackID)
	return err
}

const createProject = `-- name: CreateProject :one
INSERT INTO projects (title, slug, thumbnail, content, demo_url, repo_url, is_featured, published_at, category_id)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9) RETURNING id, title, slug, thumbnail, content, demo_url, repo_url, is_featured, published_at, column_order, category_id, created_at, updated_at
`

type CreateProjectParams struct {
	Title       string         `json:"title"`
	Slug        string         `json:"slug"`
	Thumbnail   sql.NullString `json:"thumbnail"`
	Content     sql.NullString `json:"content"`
	DemoUrl     sql.NullString `json:"demo_url"`
	RepoUrl     sql.NullString `json:"repo_url"`
	IsFeatured  sql.NullBool   `json:"is_featured"`
	PublishedAt sql.NullTime   `json:"published_at"`
	CategoryID  sql.NullInt64  `json:"category_id"`
}

func (q *Queries) CreateProject(ctx context.Context, arg CreateProjectParams) (Project, error) {
	row := q.db.QueryRowContext(ctx, createProject,
		arg.Title,
		arg.Slug,
		arg.Thumbnail,
		arg.Content,
		arg.DemoUrl,
		arg.RepoUrl,
		arg.IsFeatured,
		arg.PublishedAt,
		arg.CategoryID,
	)
	var i Project
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Slug,
		&i.Thumbnail,
		&i.Content,
		&i.DemoUrl,
		&i.RepoUrl,
		&i.IsFeatured,
		&i.PublishedAt,
		&i.ColumnOrder,
		&i.CategoryID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteProject = `-- name: DeleteProject :exec
DELETE
FROM projects
WHERE id = $1
`

func (q *Queries) DeleteProject(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, deleteProject, id)
	return err
}

const deleteProjectTags = `-- name: DeleteProjectTags :exec
DELETE
FROM project_tags
WHERE project_id = $1
`

func (q *Queries) DeleteProjectTags(ctx context.Context, projectID int64) error {
	_, err := q.db.ExecContext(ctx, deleteProjectTags, projectID)
	return err
}

const deleteProjectTechStacks = `-- name: DeleteProjectTechStacks :exec
DELETE
FROM project_tech_stacks
WHERE project_id = $1
`

func (q *Queries) DeleteProjectTechStacks(ctx context.Context, projectID int64) error {
	_, err := q.db.ExecContext(ctx, deleteProjectTechStacks, projectID)
	return err
}

const getProject = `-- name: GetProject :one
SELECT id, title, slug, thumbnail, content, demo_url, repo_url, is_featured, published_at, column_order, category_id, created_at, updated_at
FROM projects
WHERE id = $1 LIMIT 1
`

func (q *Queries) GetProject(ctx context.Context, id int64) (Project, error) {
	row := q.db.QueryRowContext(ctx, getProject, id)
	var i Project
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Slug,
		&i.Thumbnail,
		&i.Content,
		&i.DemoUrl,
		&i.RepoUrl,
		&i.IsFeatured,
		&i.PublishedAt,
		&i.ColumnOrder,
		&i.CategoryID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getProjects = `-- name: GetProjects :many
SELECT id, title, slug, thumbnail, content, demo_url, repo_url, is_featured, published_at, column_order, category_id, created_at, updated_at
FROM projects
ORDER BY created_at DESC
`

func (q *Queries) GetProjects(ctx context.Context) ([]Project, error) {
	rows, err := q.db.QueryContext(ctx, getProjects)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Project
	for rows.Next() {
		var i Project
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Slug,
			&i.Thumbnail,
			&i.Content,
			&i.DemoUrl,
			&i.RepoUrl,
			&i.IsFeatured,
			&i.PublishedAt,
			&i.ColumnOrder,
			&i.CategoryID,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getTagsByProjectID = `-- name: GetTagsByProjectID :many
SELECT t.id, t.name, t.slug, t.color, t.category_id, t.created_at, t.updated_at
FROM tags t
         JOIN project_tags pt ON t.id = pt.tag_id
WHERE pt.project_id = $1
`

func (q *Queries) GetTagsByProjectID(ctx context.Context, projectID int64) ([]Tag, error) {
	rows, err := q.db.QueryContext(ctx, getTagsByProjectID, projectID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Tag
	for rows.Next() {
		var i Tag
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Slug,
			&i.Color,
			&i.CategoryID,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getTechStacksByProjectID = `-- name: GetTechStacksByProjectID :many
SELECT ts.id, ts.name, ts.slug, ts.icon, ts.column_order, ts.created_at, ts.updated_at
FROM tech_stacks ts
         JOIN project_tech_stacks pts ON ts.id = pts.tech_stack_id
WHERE pts.project_id = $1
`

func (q *Queries) GetTechStacksByProjectID(ctx context.Context, projectID int64) ([]TechStack, error) {
	rows, err := q.db.QueryContext(ctx, getTechStacksByProjectID, projectID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []TechStack
	for rows.Next() {
		var i TechStack
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Slug,
			&i.Icon,
			&i.ColumnOrder,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateProject = `-- name: UpdateProject :one
UPDATE projects
SET title       = $2,
    slug        = $3,
    thumbnail   = $4,
    content     = $5,
    demo_url    = $6,
    repo_url    = $7,
    category_id = $8,
    updated_at  = now()
WHERE id = $1 RETURNING id, title, slug, thumbnail, content, demo_url, repo_url, is_featured, published_at, column_order, category_id, created_at, updated_at
`

type UpdateProjectParams struct {
	ID         int64          `json:"id"`
	Title      string         `json:"title"`
	Slug       string         `json:"slug"`
	Thumbnail  sql.NullString `json:"thumbnail"`
	Content    sql.NullString `json:"content"`
	DemoUrl    sql.NullString `json:"demo_url"`
	RepoUrl    sql.NullString `json:"repo_url"`
	CategoryID sql.NullInt64  `json:"category_id"`
}

func (q *Queries) UpdateProject(ctx context.Context, arg UpdateProjectParams) (Project, error) {
	row := q.db.QueryRowContext(ctx, updateProject,
		arg.ID,
		arg.Title,
		arg.Slug,
		arg.Thumbnail,
		arg.Content,
		arg.DemoUrl,
		arg.RepoUrl,
		arg.CategoryID,
	)
	var i Project
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Slug,
		&i.Thumbnail,
		&i.Content,
		&i.DemoUrl,
		&i.RepoUrl,
		&i.IsFeatured,
		&i.PublishedAt,
		&i.ColumnOrder,
		&i.CategoryID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
