// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: project.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const addTagToProject = `-- name: AddTagToProject :exec
INSERT INTO project_tags (project_id, tag_id)
VALUES ($1, $2)
`

type AddTagToProjectParams struct {
	ProjectID int64 `json:"project_id"`
	TagID     int64 `json:"tag_id"`
}

func (q *Queries) AddTagToProject(ctx context.Context, arg AddTagToProjectParams) error {
	_, err := q.db.Exec(ctx, addTagToProject, arg.ProjectID, arg.TagID)
	return err
}

const addTechStackToProject = `-- name: AddTechStackToProject :exec
INSERT INTO project_tech_stacks (project_id, tech_stack_id)
VALUES ($1, $2)
`

type AddTechStackToProjectParams struct {
	ProjectID   int64 `json:"project_id"`
	TechStackID int64 `json:"tech_stack_id"`
}

func (q *Queries) AddTechStackToProject(ctx context.Context, arg AddTechStackToProjectParams) error {
	_, err := q.db.Exec(ctx, addTechStackToProject, arg.ProjectID, arg.TechStackID)
	return err
}

const attachTagToProject = `-- name: AttachTagToProject :exec
INSERT INTO project_tags (project_id, tag_id)
VALUES ($1, $2)
`

type AttachTagToProjectParams struct {
	ProjectID int64 `json:"project_id"`
	TagID     int64 `json:"tag_id"`
}

func (q *Queries) AttachTagToProject(ctx context.Context, arg AttachTagToProjectParams) error {
	_, err := q.db.Exec(ctx, attachTagToProject, arg.ProjectID, arg.TagID)
	return err
}

const attachTechStackToProject = `-- name: AttachTechStackToProject :exec

INSERT INTO project_tech_stacks (project_id, tech_stack_id)
VALUES ($1, $2)
`

type AttachTechStackToProjectParams struct {
	ProjectID   int64 `json:"project_id"`
	TechStackID int64 `json:"tech_stack_id"`
}

// =============================================
// PIVOT TABLE QUERIES
// =============================================
func (q *Queries) AttachTechStackToProject(ctx context.Context, arg AttachTechStackToProjectParams) error {
	_, err := q.db.Exec(ctx, attachTechStackToProject, arg.ProjectID, arg.TechStackID)
	return err
}

const createProject = `-- name: CreateProject :one
INSERT INTO projects (title, slug, thumbnail, content, demo_url, repo_url, is_featured, published_at, category_id)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9) RETURNING id, title, slug, thumbnail, content, demo_url, repo_url, is_featured, published_at, column_order, category_id, created_at, updated_at
`

type CreateProjectParams struct {
	Title       string             `json:"title"`
	Slug        string             `json:"slug"`
	Thumbnail   pgtype.Text        `json:"thumbnail"`
	Content     pgtype.Text        `json:"content"`
	DemoUrl     pgtype.Text        `json:"demo_url"`
	RepoUrl     pgtype.Text        `json:"repo_url"`
	IsFeatured  pgtype.Bool        `json:"is_featured"`
	PublishedAt pgtype.Timestamptz `json:"published_at"`
	CategoryID  pgtype.Int8        `json:"category_id"`
}

func (q *Queries) CreateProject(ctx context.Context, arg CreateProjectParams) (Project, error) {
	row := q.db.QueryRow(ctx, createProject,
		arg.Title,
		arg.Slug,
		arg.Thumbnail,
		arg.Content,
		arg.DemoUrl,
		arg.RepoUrl,
		arg.IsFeatured,
		arg.PublishedAt,
		arg.CategoryID,
	)
	var i Project
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Slug,
		&i.Thumbnail,
		&i.Content,
		&i.DemoUrl,
		&i.RepoUrl,
		&i.IsFeatured,
		&i.PublishedAt,
		&i.ColumnOrder,
		&i.CategoryID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteProject = `-- name: DeleteProject :one
DELETE
FROM projects
WHERE id = $1 RETURNING id, title, slug, thumbnail, content, demo_url, repo_url, is_featured, published_at, column_order, category_id, created_at, updated_at
`

func (q *Queries) DeleteProject(ctx context.Context, id int64) (Project, error) {
	row := q.db.QueryRow(ctx, deleteProject, id)
	var i Project
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Slug,
		&i.Thumbnail,
		&i.Content,
		&i.DemoUrl,
		&i.RepoUrl,
		&i.IsFeatured,
		&i.PublishedAt,
		&i.ColumnOrder,
		&i.CategoryID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteProjectTags = `-- name: DeleteProjectTags :exec
DELETE
FROM project_tags
WHERE project_id = $1
`

func (q *Queries) DeleteProjectTags(ctx context.Context, projectID int64) error {
	_, err := q.db.Exec(ctx, deleteProjectTags, projectID)
	return err
}

const deleteProjectTechStacks = `-- name: DeleteProjectTechStacks :exec
DELETE
FROM project_tech_stacks
WHERE project_id = $1
`

func (q *Queries) DeleteProjectTechStacks(ctx context.Context, projectID int64) error {
	_, err := q.db.Exec(ctx, deleteProjectTechStacks, projectID)
	return err
}

const getCategoriesByIDs = `-- name: GetCategoriesByIDs :many
SELECT id, name, slug, color, created_at, updated_at
FROM categories
WHERE id = ANY ($1::int[])
`

func (q *Queries) GetCategoriesByIDs(ctx context.Context, categoryIds []int32) ([]Category, error) {
	rows, err := q.db.Query(ctx, getCategoriesByIDs, categoryIds)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Category
	for rows.Next() {
		var i Category
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Slug,
			&i.Color,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getProject = `-- name: GetProject :one
SELECT id, title, slug, thumbnail, content, demo_url, repo_url, is_featured, published_at, column_order, category_id, created_at, updated_at
FROM projects
WHERE id = $1 LIMIT 1
`

func (q *Queries) GetProject(ctx context.Context, id int64) (Project, error) {
	row := q.db.QueryRow(ctx, getProject, id)
	var i Project
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Slug,
		&i.Thumbnail,
		&i.Content,
		&i.DemoUrl,
		&i.RepoUrl,
		&i.IsFeatured,
		&i.PublishedAt,
		&i.ColumnOrder,
		&i.CategoryID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getProjectByColumnOrder = `-- name: GetProjectByColumnOrder :one
SELECT id, title, slug, thumbnail, content, demo_url, repo_url, is_featured, published_at, column_order, category_id, created_at, updated_at
FROM projects
WHERE column_order = $1 LIMIT 1
`

func (q *Queries) GetProjectByColumnOrder(ctx context.Context, columnOrder int32) (Project, error) {
	row := q.db.QueryRow(ctx, getProjectByColumnOrder, columnOrder)
	var i Project
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Slug,
		&i.Thumbnail,
		&i.Content,
		&i.DemoUrl,
		&i.RepoUrl,
		&i.IsFeatured,
		&i.PublishedAt,
		&i.ColumnOrder,
		&i.CategoryID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getProjects = `-- name: GetProjects :many
SELECT id, title, slug, thumbnail, content, demo_url, repo_url, is_featured, published_at, column_order, category_id, created_at, updated_at
FROM projects
ORDER BY column_order ASC
`

func (q *Queries) GetProjects(ctx context.Context) ([]Project, error) {
	rows, err := q.db.Query(ctx, getProjects)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Project
	for rows.Next() {
		var i Project
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Slug,
			&i.Thumbnail,
			&i.Content,
			&i.DemoUrl,
			&i.RepoUrl,
			&i.IsFeatured,
			&i.PublishedAt,
			&i.ColumnOrder,
			&i.CategoryID,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getTagsByProjectID = `-- name: GetTagsByProjectID :many
SELECT project_tags.project_id, tags.id, tags.name, tags.slug, tags.color, tags.category_id, tags.created_at, tags.updated_at
FROM tags
         JOIN project_tags ON tags.id = project_tags.tag_id
WHERE project_tags.project_id = ANY ($1::int[])
`

type GetTagsByProjectIDRow struct {
	ProjectID  int64              `json:"project_id"`
	ID         int64              `json:"id"`
	Name       string             `json:"name"`
	Slug       string             `json:"slug"`
	Color      pgtype.Text        `json:"color"`
	CategoryID pgtype.Int8        `json:"category_id"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
	UpdatedAt  pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) GetTagsByProjectID(ctx context.Context, projectIds []int32) ([]GetTagsByProjectIDRow, error) {
	rows, err := q.db.Query(ctx, getTagsByProjectID, projectIds)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetTagsByProjectIDRow
	for rows.Next() {
		var i GetTagsByProjectIDRow
		if err := rows.Scan(
			&i.ProjectID,
			&i.ID,
			&i.Name,
			&i.Slug,
			&i.Color,
			&i.CategoryID,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getTechStacksByProjectID = `-- name: GetTechStacksByProjectID :many
SELECT project_tech_stacks.project_id, tech_stacks.id, tech_stacks.name, tech_stacks.slug, tech_stacks.icon, tech_stacks.column_order, tech_stacks.created_at, tech_stacks.updated_at, tech_stacks.tech_stack_category_id
FROM tech_stacks
         JOIN project_tech_stacks ON tech_stacks.id = project_tech_stacks.tech_stack_id
WHERE project_tech_stacks.project_id = ANY ($1::int[])
ORDER BY tech_stacks.column_order ASC
`

type GetTechStacksByProjectIDRow struct {
	ProjectID           int64              `json:"project_id"`
	ID                  int64              `json:"id"`
	Name                string             `json:"name"`
	Slug                string             `json:"slug"`
	Icon                pgtype.Text        `json:"icon"`
	ColumnOrder         int32              `json:"column_order"`
	CreatedAt           pgtype.Timestamptz `json:"created_at"`
	UpdatedAt           pgtype.Timestamptz `json:"updated_at"`
	TechStackCategoryID pgtype.Int8        `json:"tech_stack_category_id"`
}

func (q *Queries) GetTechStacksByProjectID(ctx context.Context, projectIds []int32) ([]GetTechStacksByProjectIDRow, error) {
	rows, err := q.db.Query(ctx, getTechStacksByProjectID, projectIds)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetTechStacksByProjectIDRow
	for rows.Next() {
		var i GetTechStacksByProjectIDRow
		if err := rows.Scan(
			&i.ProjectID,
			&i.ID,
			&i.Name,
			&i.Slug,
			&i.Icon,
			&i.ColumnOrder,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.TechStackCategoryID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateProject = `-- name: UpdateProject :one
UPDATE projects
SET title       = $2,
    slug        = $3,
    thumbnail   = $4,
    content     = $5,
    demo_url    = $6,
    repo_url    = $7,
    category_id = $8,
    published_at = $9,
    updated_at  = now()
WHERE id = $1 RETURNING id, title, slug, thumbnail, content, demo_url, repo_url, is_featured, published_at, column_order, category_id, created_at, updated_at
`

type UpdateProjectParams struct {
	ID          int64              `json:"id"`
	Title       string             `json:"title"`
	Slug        string             `json:"slug"`
	Thumbnail   pgtype.Text        `json:"thumbnail"`
	Content     pgtype.Text        `json:"content"`
	DemoUrl     pgtype.Text        `json:"demo_url"`
	RepoUrl     pgtype.Text        `json:"repo_url"`
	CategoryID  pgtype.Int8        `json:"category_id"`
	PublishedAt pgtype.Timestamptz `json:"published_at"`
}

func (q *Queries) UpdateProject(ctx context.Context, arg UpdateProjectParams) (Project, error) {
	row := q.db.QueryRow(ctx, updateProject,
		arg.ID,
		arg.Title,
		arg.Slug,
		arg.Thumbnail,
		arg.Content,
		arg.DemoUrl,
		arg.RepoUrl,
		arg.CategoryID,
		arg.PublishedAt,
	)
	var i Project
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Slug,
		&i.Thumbnail,
		&i.Content,
		&i.DemoUrl,
		&i.RepoUrl,
		&i.IsFeatured,
		&i.PublishedAt,
		&i.ColumnOrder,
		&i.CategoryID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateProjectColumnOrder = `-- name: UpdateProjectColumnOrder :one
UPDATE projects
SET column_order = $2,
    updated_at = now()
WHERE id = $1 RETURNING id, title, slug, thumbnail, content, demo_url, repo_url, is_featured, published_at, column_order, category_id, created_at, updated_at
`

type UpdateProjectColumnOrderParams struct {
	ID          int64 `json:"id"`
	ColumnOrder int32 `json:"column_order"`
}

func (q *Queries) UpdateProjectColumnOrder(ctx context.Context, arg UpdateProjectColumnOrderParams) (Project, error) {
	row := q.db.QueryRow(ctx, updateProjectColumnOrder, arg.ID, arg.ColumnOrder)
	var i Project
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Slug,
		&i.Thumbnail,
		&i.Content,
		&i.DemoUrl,
		&i.RepoUrl,
		&i.IsFeatured,
		&i.PublishedAt,
		&i.ColumnOrder,
		&i.CategoryID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
