// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: tag.sql

package db

import (
	"context"
	"database/sql"
)

const createTag = `-- name: CreateTag :one
INSERT INTO tags (name, slug, color, category_id)
VALUES ($1, $2, $3, $4) RETURNING id, name, slug, color, category_id, created_at
`

type CreateTagParams struct {
	Name       string         `json:"name"`
	Slug       string         `json:"slug"`
	Color      sql.NullString `json:"color"`
	CategoryID sql.NullInt64  `json:"category_id"`
}

func (q *Queries) CreateTag(ctx context.Context, arg CreateTagParams) (Tag, error) {
	row := q.db.QueryRowContext(ctx, createTag,
		arg.Name,
		arg.Slug,
		arg.Color,
		arg.CategoryID,
	)
	var i Tag
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Slug,
		&i.Color,
		&i.CategoryID,
		&i.CreatedAt,
	)
	return i, err
}

const listTags = `-- name: ListTags :many
SELECT id, name, slug, color, category_id, created_at
FROM tags
ORDER BY name
`

func (q *Queries) ListTags(ctx context.Context) ([]Tag, error) {
	rows, err := q.db.QueryContext(ctx, listTags)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Tag
	for rows.Next() {
		var i Tag
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Slug,
			&i.Color,
			&i.CategoryID,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
