// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: tag.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createTag = `-- name: CreateTag :one
INSERT INTO tags (name, slug, color, category_id)
VALUES ($1, $2, $3, $4) RETURNING id, name, slug, color, category_id, created_at, updated_at
`

type CreateTagParams struct {
	Name       string      `json:"name"`
	Slug       string      `json:"slug"`
	Color      pgtype.Text `json:"color"`
	CategoryID pgtype.Int8 `json:"category_id"`
}

func (q *Queries) CreateTag(ctx context.Context, arg CreateTagParams) (Tag, error) {
	row := q.db.QueryRow(ctx, createTag,
		arg.Name,
		arg.Slug,
		arg.Color,
		arg.CategoryID,
	)
	var i Tag
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Slug,
		&i.Color,
		&i.CategoryID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteTag = `-- name: DeleteTag :one
DELETE
FROM tags
WHERE id = $1 RETURNING id, name, slug, color, category_id, created_at, updated_at
`

func (q *Queries) DeleteTag(ctx context.Context, id int64) (Tag, error) {
	row := q.db.QueryRow(ctx, deleteTag, id)
	var i Tag
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Slug,
		&i.Color,
		&i.CategoryID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getTag = `-- name: GetTag :one
SELECT id, name, slug, color, category_id, created_at, updated_at
FROM tags
WHERE id = $1 LIMIT 1
`

func (q *Queries) GetTag(ctx context.Context, id int64) (Tag, error) {
	row := q.db.QueryRow(ctx, getTag, id)
	var i Tag
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Slug,
		&i.Color,
		&i.CategoryID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getTags = `-- name: GetTags :many
SELECT id, name, slug, color, category_id, created_at, updated_at
FROM tags
ORDER BY name
`

func (q *Queries) GetTags(ctx context.Context) ([]Tag, error) {
	rows, err := q.db.Query(ctx, getTags)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Tag
	for rows.Next() {
		var i Tag
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Slug,
			&i.Color,
			&i.CategoryID,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateTag = `-- name: UpdateTag :one
UPDATE tags
SET name        = $2,
    slug        = $3,
    color       = $4,
    category_id = $5,
    updated_at  = now()
WHERE id = $1 RETURNING id, name, slug, color, category_id, created_at, updated_at
`

type UpdateTagParams struct {
	ID         int64       `json:"id"`
	Name       string      `json:"name"`
	Slug       string      `json:"slug"`
	Color      pgtype.Text `json:"color"`
	CategoryID pgtype.Int8 `json:"category_id"`
}

func (q *Queries) UpdateTag(ctx context.Context, arg UpdateTagParams) (Tag, error) {
	row := q.db.QueryRow(ctx, updateTag,
		arg.ID,
		arg.Name,
		arg.Slug,
		arg.Color,
		arg.CategoryID,
	)
	var i Tag
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Slug,
		&i.Color,
		&i.CategoryID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
