// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: tech_stack.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createTechStack = `-- name: CreateTechStack :one
Insert into tech_stacks (name, slug, icon, tech_stack_category_id)
values ($1, $2, $3, $4) returning id, name, slug, icon, column_order, created_at, updated_at, tech_stack_category_id
`

type CreateTechStackParams struct {
	Name                string      `json:"name"`
	Slug                string      `json:"slug"`
	Icon                pgtype.Text `json:"icon"`
	TechStackCategoryID pgtype.Int8 `json:"tech_stack_category_id"`
}

func (q *Queries) CreateTechStack(ctx context.Context, arg CreateTechStackParams) (TechStack, error) {
	row := q.db.QueryRow(ctx, createTechStack,
		arg.Name,
		arg.Slug,
		arg.Icon,
		arg.TechStackCategoryID,
	)
	var i TechStack
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Slug,
		&i.Icon,
		&i.ColumnOrder,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.TechStackCategoryID,
	)
	return i, err
}

const deleteTechStack = `-- name: DeleteTechStack :one
delete
from tech_stacks
where id = $1 returning id, name, slug, icon, column_order, created_at, updated_at, tech_stack_category_id
`

func (q *Queries) DeleteTechStack(ctx context.Context, id int64) (TechStack, error) {
	row := q.db.QueryRow(ctx, deleteTechStack, id)
	var i TechStack
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Slug,
		&i.Icon,
		&i.ColumnOrder,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.TechStackCategoryID,
	)
	return i, err
}

const getTechStack = `-- name: GetTechStack :one
select id, name, slug, icon, column_order, created_at, updated_at, tech_stack_category_id
from tech_stacks
where id = $1 limit 1
`

func (q *Queries) GetTechStack(ctx context.Context, id int64) (TechStack, error) {
	row := q.db.QueryRow(ctx, getTechStack, id)
	var i TechStack
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Slug,
		&i.Icon,
		&i.ColumnOrder,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.TechStackCategoryID,
	)
	return i, err
}

const getTechStackByColumnOrder = `-- name: GetTechStackByColumnOrder :one
SELECT id, name, slug, icon, column_order, created_at, updated_at, tech_stack_category_id
FROM tech_stacks
WHERE column_order = $1
LIMIT 1
`

func (q *Queries) GetTechStackByColumnOrder(ctx context.Context, columnOrder int32) (TechStack, error) {
	row := q.db.QueryRow(ctx, getTechStackByColumnOrder, columnOrder)
	var i TechStack
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Slug,
		&i.Icon,
		&i.ColumnOrder,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.TechStackCategoryID,
	)
	return i, err
}

const getTechStacks = `-- name: GetTechStacks :many
select id, name, slug, icon, column_order, created_at, updated_at, tech_stack_category_id
from tech_stacks
order by column_order
`

func (q *Queries) GetTechStacks(ctx context.Context) ([]TechStack, error) {
	rows, err := q.db.Query(ctx, getTechStacks)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []TechStack
	for rows.Next() {
		var i TechStack
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Slug,
			&i.Icon,
			&i.ColumnOrder,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.TechStackCategoryID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateTechStack = `-- name: UpdateTechStack :one
update tech_stacks
set name                   = $2,
    slug                   = $3,
    icon                   = $4,
    tech_stack_category_id = $5,
    updated_at             = now()
where id = $1 returning id, name, slug, icon, column_order, created_at, updated_at, tech_stack_category_id
`

type UpdateTechStackParams struct {
	ID                  int64       `json:"id"`
	Name                string      `json:"name"`
	Slug                string      `json:"slug"`
	Icon                pgtype.Text `json:"icon"`
	TechStackCategoryID pgtype.Int8 `json:"tech_stack_category_id"`
}

func (q *Queries) UpdateTechStack(ctx context.Context, arg UpdateTechStackParams) (TechStack, error) {
	row := q.db.QueryRow(ctx, updateTechStack,
		arg.ID,
		arg.Name,
		arg.Slug,
		arg.Icon,
		arg.TechStackCategoryID,
	)
	var i TechStack
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Slug,
		&i.Icon,
		&i.ColumnOrder,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.TechStackCategoryID,
	)
	return i, err
}

const updateTechStackColumnOrder = `-- name: UpdateTechStackColumnOrder :one
update tech_stacks
set column_order = $2,
    updated_at   = now()
where id = $1 returning id, name, slug, icon, column_order, created_at, updated_at, tech_stack_category_id
`

type UpdateTechStackColumnOrderParams struct {
	ID          int64 `json:"id"`
	ColumnOrder int32 `json:"column_order"`
}

func (q *Queries) UpdateTechStackColumnOrder(ctx context.Context, arg UpdateTechStackColumnOrderParams) (TechStack, error) {
	row := q.db.QueryRow(ctx, updateTechStackColumnOrder, arg.ID, arg.ColumnOrder)
	var i TechStack
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Slug,
		&i.Icon,
		&i.ColumnOrder,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.TechStackCategoryID,
	)
	return i, err
}
