// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: tech_stack.sql

package db

import (
	"context"
	"database/sql"
)

const createTechStack = `-- name: CreateTechStack :one
Insert into tech_stacks (name, slug, icon)
values ($1, $2, $3) returning id, name, slug, icon, column_order, created_at, updated_at
`

type CreateTechStackParams struct {
	Name string         `json:"name"`
	Slug string         `json:"slug"`
	Icon sql.NullString `json:"icon"`
}

func (q *Queries) CreateTechStack(ctx context.Context, arg CreateTechStackParams) (TechStack, error) {
	row := q.db.QueryRowContext(ctx, createTechStack, arg.Name, arg.Slug, arg.Icon)
	var i TechStack
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Slug,
		&i.Icon,
		&i.ColumnOrder,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteTechStack = `-- name: DeleteTechStack :one
delete
from tech_stacks
where id = $1 returning id, name, slug, icon, column_order, created_at, updated_at
`

func (q *Queries) DeleteTechStack(ctx context.Context, id int64) (TechStack, error) {
	row := q.db.QueryRowContext(ctx, deleteTechStack, id)
	var i TechStack
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Slug,
		&i.Icon,
		&i.ColumnOrder,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getTechStack = `-- name: GetTechStack :one
select id, name, slug, icon, column_order, created_at, updated_at
from tech_stacks
where id = $1 limit 1
`

func (q *Queries) GetTechStack(ctx context.Context, id int64) (TechStack, error) {
	row := q.db.QueryRowContext(ctx, getTechStack, id)
	var i TechStack
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Slug,
		&i.Icon,
		&i.ColumnOrder,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getTechStacks = `-- name: GetTechStacks :many
select id, name, slug, icon, column_order, created_at, updated_at
from tech_stacks
order by column_order
`

func (q *Queries) GetTechStacks(ctx context.Context) ([]TechStack, error) {
	rows, err := q.db.QueryContext(ctx, getTechStacks)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []TechStack
	for rows.Next() {
		var i TechStack
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Slug,
			&i.Icon,
			&i.ColumnOrder,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateTechStack = `-- name: UpdateTechStack :one
update tech_stacks
set name         = $2,
    slug         = $3,
    icon         = $4,
    updated_at   = now()
where id = $1 returning id, name, slug, icon, column_order, created_at, updated_at
`

type UpdateTechStackParams struct {
	ID   int64          `json:"id"`
	Name string         `json:"name"`
	Slug string         `json:"slug"`
	Icon sql.NullString `json:"icon"`
}

func (q *Queries) UpdateTechStack(ctx context.Context, arg UpdateTechStackParams) (TechStack, error) {
	row := q.db.QueryRowContext(ctx, updateTechStack,
		arg.ID,
		arg.Name,
		arg.Slug,
		arg.Icon,
	)
	var i TechStack
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Slug,
		&i.Icon,
		&i.ColumnOrder,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
