// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: tech_stack_category.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createTechStackCategory = `-- name: CreateTechStackCategory :one
INSERT INTO tech_stack_categories (name, slug, color, created_at, updated_at)
VALUES ($1, $2, $3, now(), now()) RETURNING id, name, slug, color, created_at, updated_at
`

type CreateTechStackCategoryParams struct {
	Name  string      `json:"name"`
	Slug  string      `json:"slug"`
	Color pgtype.Text `json:"color"`
}

func (q *Queries) CreateTechStackCategory(ctx context.Context, arg CreateTechStackCategoryParams) (TechStackCategory, error) {
	row := q.db.QueryRow(ctx, createTechStackCategory, arg.Name, arg.Slug, arg.Color)
	var i TechStackCategory
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Slug,
		&i.Color,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteTechStackCategory = `-- name: DeleteTechStackCategory :one
DELETE FROM tech_stack_categories
WHERE id = $1 RETURNING id, name, slug, color, created_at, updated_at
`

func (q *Queries) DeleteTechStackCategory(ctx context.Context, id int64) (TechStackCategory, error) {
	row := q.db.QueryRow(ctx, deleteTechStackCategory, id)
	var i TechStackCategory
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Slug,
		&i.Color,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getTechStackCategories = `-- name: GetTechStackCategories :many
SELECT id, name, slug, color, created_at, updated_at FROM tech_stack_categories
ORDER BY id
`

func (q *Queries) GetTechStackCategories(ctx context.Context) ([]TechStackCategory, error) {
	rows, err := q.db.Query(ctx, getTechStackCategories)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []TechStackCategory
	for rows.Next() {
		var i TechStackCategory
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Slug,
			&i.Color,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getTechStackCategory = `-- name: GetTechStackCategory :one
SELECT id, name, slug, color, created_at, updated_at FROM tech_stack_categories
WHERE id = $1 LIMIT 1
`

func (q *Queries) GetTechStackCategory(ctx context.Context, id int64) (TechStackCategory, error) {
	row := q.db.QueryRow(ctx, getTechStackCategory, id)
	var i TechStackCategory
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Slug,
		&i.Color,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateTechStackCategory = `-- name: UpdateTechStackCategory :one
UPDATE tech_stack_categories
SET name = $2,
    slug = $3,
    color = $4,
    updated_at = now()
WHERE id = $1 RETURNING id, name, slug, color, created_at, updated_at
`

type UpdateTechStackCategoryParams struct {
	ID    int64       `json:"id"`
	Name  string      `json:"name"`
	Slug  string      `json:"slug"`
	Color pgtype.Text `json:"color"`
}

func (q *Queries) UpdateTechStackCategory(ctx context.Context, arg UpdateTechStackCategoryParams) (TechStackCategory, error) {
	row := q.db.QueryRow(ctx, updateTechStackCategory,
		arg.ID,
		arg.Name,
		arg.Slug,
		arg.Color,
	)
	var i TechStackCategory
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Slug,
		&i.Color,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
