// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: tech_stack.sql

package db

import (
	"context"
)

const listTechStacks = `-- name: ListTechStacks :many
select id, name, slug, icon, created_at
from tech_stacks
`

func (q *Queries) ListTechStacks(ctx context.Context) ([]TechStack, error) {
	rows, err := q.db.QueryContext(ctx, listTechStacks)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []TechStack
	for rows.Next() {
		var i TechStack
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Slug,
			&i.Icon,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
