// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: work_experience.sql

package db

import (
	"context"
	"database/sql"
)

const attachTagToWorkExperience = `-- name: AttachTagToWorkExperience :exec
INSERT INTO work_experience_tags (work_experience_id, tag_id)
VALUES ($1, $2)
`

type AttachTagToWorkExperienceParams struct {
	WorkExperienceID int64 `json:"work_experience_id"`
	TagID            int64 `json:"tag_id"`
}

func (q *Queries) AttachTagToWorkExperience(ctx context.Context, arg AttachTagToWorkExperienceParams) error {
	_, err := q.db.ExecContext(ctx, attachTagToWorkExperience, arg.WorkExperienceID, arg.TagID)
	return err
}

const attachTechStackToWorkExperience = `-- name: AttachTechStackToWorkExperience :exec
INSERT INTO work_experience_tech_stacks (work_experience_id, tech_stack_id)
VALUES ($1, $2)
`

type AttachTechStackToWorkExperienceParams struct {
	WorkExperienceID int64 `json:"work_experience_id"`
	TechStackID      int64 `json:"tech_stack_id"`
}

func (q *Queries) AttachTechStackToWorkExperience(ctx context.Context, arg AttachTechStackToWorkExperienceParams) error {
	_, err := q.db.ExecContext(ctx, attachTechStackToWorkExperience, arg.WorkExperienceID, arg.TechStackID)
	return err
}

const createWorkExperience = `-- name: CreateWorkExperience :one
INSERT INTO work_experiences (company, position, location, start_date, end_date, is_current, description)
VALUES ($1, $2, $3, $4, $5, $6, $7) RETURNING id, company, position, location, start_date, end_date, is_current, description, created_at
`

type CreateWorkExperienceParams struct {
	Company     string         `json:"company"`
	Position    string         `json:"position"`
	Location    sql.NullString `json:"location"`
	StartDate   sql.NullString `json:"start_date"`
	EndDate     sql.NullString `json:"end_date"`
	IsCurrent   sql.NullBool   `json:"is_current"`
	Description sql.NullString `json:"description"`
}

func (q *Queries) CreateWorkExperience(ctx context.Context, arg CreateWorkExperienceParams) (WorkExperience, error) {
	row := q.db.QueryRowContext(ctx, createWorkExperience,
		arg.Company,
		arg.Position,
		arg.Location,
		arg.StartDate,
		arg.EndDate,
		arg.IsCurrent,
		arg.Description,
	)
	var i WorkExperience
	err := row.Scan(
		&i.ID,
		&i.Company,
		&i.Position,
		&i.Location,
		&i.StartDate,
		&i.EndDate,
		&i.IsCurrent,
		&i.Description,
		&i.CreatedAt,
	)
	return i, err
}

const getWorkExperiences = `-- name: GetWorkExperiences :one
SELECT id, company, position, location, start_date, end_date, is_current, description, created_at
FROM work_experiences
WHERE id = $1 LIMIT 1
`

func (q *Queries) GetWorkExperiences(ctx context.Context, id int64) (WorkExperience, error) {
	row := q.db.QueryRowContext(ctx, getWorkExperiences, id)
	var i WorkExperience
	err := row.Scan(
		&i.ID,
		&i.Company,
		&i.Position,
		&i.Location,
		&i.StartDate,
		&i.EndDate,
		&i.IsCurrent,
		&i.Description,
		&i.CreatedAt,
	)
	return i, err
}

const listWorkExperiences = `-- name: ListWorkExperiences :many
SELECT id, company, position, location, start_date, end_date, is_current, description, created_at
FROM work_experiences
ORDER BY created_at DESC
`

func (q *Queries) ListWorkExperiences(ctx context.Context) ([]WorkExperience, error) {
	rows, err := q.db.QueryContext(ctx, listWorkExperiences)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []WorkExperience
	for rows.Next() {
		var i WorkExperience
		if err := rows.Scan(
			&i.ID,
			&i.Company,
			&i.Position,
			&i.Location,
			&i.StartDate,
			&i.EndDate,
			&i.IsCurrent,
			&i.Description,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
